import React from 'react';
import { IBM_Plex_Sans } from 'next/font/google';
import { ConfigProvider } from 'antd';

import StyledComponentsRegistry from '../lib/AntdRegistry';
import theme from '@/lib/themeConfig';

import './globals.css';

const ibmPlexSans = IBM_Plex_Sans({
    subsets: ['latin'],
    weight: ['100', '200', '300', '400', '500', '600', '700'],
});

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
    <html lang="en">
        <ConfigProvider theme={theme}>
            <body className={ibmPlexSans.className}>
                <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
            </body>
        </ConfigProvider>
    </html>
);

export default RootLayout;
